function(collect_bean_modules output_var source_dir)
  file(GLOB_RECURSE candidate_modules CONFIGURE_DEPENDS "${source_dir}/*.cppm")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${candidate_modules})

  set(bean_modules "")

  foreach(candidate_module IN LISTS candidate_modules)
    file(READ "${candidate_module}" content)

    if(content MATCHES "///[ \t]*Bean")
      list(APPEND bean_modules "${candidate_module}")
    endif()
  endforeach()

  set(${output_var} ${bean_modules} PARENT_SCOPE)
endfunction()

function(generate_context_module output_file)
  set(options)
  set(one_value_args)
  set(multi_value_args BEAN_SOURCES)
  cmake_parse_arguments(ARG "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  if(NOT ARG_BEAN_SOURCES)
    message(FATAL_ERROR "kHg4Pq1sVa :: generate_context_module requires BEAN_SOURCES")
  endif()

  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${ARG_BEAN_SOURCES})

  set(imports "import getter;\n")
  set(fields "")
  set(public_getters "")
  set(private_factories "")
  set(bean_names "")
  set(bean_types "")
  set(bean_dependencies "")

  foreach(bean_source IN LISTS ARG_BEAN_SOURCES)
    file(READ "${bean_source}" content)

    if(NOT content MATCHES "///[ \t]*Bean")
      continue()
    endif()

    if(NOT content MATCHES "export[ \t\r\n]+module[ \t\r\n]+([A-Za-z_][A-Za-z0-9_]*)")
      message(FATAL_ERROR "Aa7Qm3tRz9 :: Cannot find exported module name in ${bean_source}")
    endif()
    set(module_name "${CMAKE_MATCH_1}")

    if(NOT content MATCHES "export[ \t\r\n]+namespace[ \t\r\n]+([A-Za-z_][A-Za-z0-9_]*)")
      message(FATAL_ERROR "Vn2xLp8Kc4 :: Cannot find exported namespace in ${bean_source}")
    endif()
    set(namespace_name "${CMAKE_MATCH_1}")

    if(NOT content MATCHES "class[ \t\r\n]+([A-Za-z_][A-Za-z0-9_]*)")
      message(FATAL_ERROR "PO8I7xeYBv :: Cannot find bean class in ${bean_source}")
    endif()
    set(class_name "${CMAKE_MATCH_1}")

    if(NOT content MATCHES "///[ \t]*Bean[ \t]+([A-Za-z_][A-Za-z0-9_]*)([^\r\n]*)")
      message(FATAL_ERROR "Lm9Qe2Rt6X :: Cannot find bean name in ${bean_source}")
    endif()
    set(bean_name "${CMAKE_MATCH_1}")
    set(dependencies_text "${CMAKE_MATCH_2}")
    string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_]*::[A-Za-z_][A-Za-z0-9_]*" dependencies "${dependencies_text}")

    set(type_name "${namespace_name}::${class_name}")

    list(FIND bean_names "${bean_name}" bean_name_index)
    if(NOT bean_name_index EQUAL -1)
      message(FATAL_ERROR "Tb3Wy8An0K :: Duplicate bean name '${bean_name}' in ${bean_source}")
    endif()

    list(FIND bean_types "${type_name}" bean_type_index)
    if(NOT bean_type_index EQUAL -1)
      message(FATAL_ERROR "Yd6Cp1Ks4M :: Duplicate bean type '${type_name}' in ${bean_source}")
    endif()

    list(APPEND bean_names "${bean_name}")
    list(APPEND bean_types "${type_name}")
    string(REPLACE ";" "|" dependency_value "${dependencies}")
    if(NOT dependency_value)
      set(dependency_value "__NO_DEPENDENCIES__")
    endif()
    list(APPEND bean_dependencies "${dependency_value}")
    string(APPEND imports "import ${module_name};\n")
  endforeach()

  list(LENGTH bean_names bean_count)
  if(bean_count EQUAL 0)
    message(FATAL_ERROR "Rs8Kx2Va0P :: No bean modules found")
  endif()

  math(EXPR last_bean_index "${bean_count} - 1")
  foreach(bean_index RANGE 0 ${last_bean_index})
    list(GET bean_names ${bean_index} bean_name)
    list(GET bean_types ${bean_index} type_name)
    list(GET bean_dependencies ${bean_index} dependency_value)
    if(dependency_value STREQUAL "__NO_DEPENDENCIES__")
      set(dependencies "")
    else()
      string(REPLACE "|" ";" dependencies "${dependency_value}")
    endif()

    string(APPEND fields "    getter::Getter<${type_name}> ${bean_name}_{&mutex_, [this] { return create_${bean_name}(); }};\n")
    string(APPEND public_getters "\n    ${type_name} *get_${bean_name}()\n    {\n      return ${bean_name}_.get();\n    }\n")

    set(constructor_args "")
    foreach(dependency IN LISTS dependencies)
      if(NOT dependency MATCHES "^([A-Za-z_][A-Za-z0-9_]*)::")
        message(FATAL_ERROR "Zr5mUd0YpN :: Cannot parse dependency '${dependency}' for bean '${bean_name}'")
      endif()

      list(FIND bean_types "${dependency}" dependency_index)
      if(dependency_index EQUAL -1)
        message(FATAL_ERROR "Nc0Vb7Dr5T :: Bean '${bean_name}' depends on unknown bean type '${dependency}'")
      endif()
      list(GET bean_names ${dependency_index} dependency_name)

      if(constructor_args)
        string(APPEND constructor_args ", ")
      endif()
      string(APPEND constructor_args "${dependency_name}_")
    endforeach()

    if(constructor_args)
      set(create_expression "new ${type_name}(${constructor_args})")
    else()
      set(create_expression "new ${type_name}()")
    endif()

    string(APPEND private_factories "\n    ${type_name} *create_${bean_name}()\n    {\n      return finish_create(${create_expression});\n    }\n")
  endforeach()

  file(WRITE "${output_file}" "// Generated by cmake/GenerateContext.cmake. Do not edit manually.\n")
  file(APPEND "${output_file}" "module;\n\n")
  file(APPEND "${output_file}" "#include <shared_mutex>\n\n")
  file(APPEND "${output_file}" "export module context;\n")
  file(APPEND "${output_file}" "${imports}\n")
  file(APPEND "${output_file}" "export namespace context {\n")
  file(APPEND "${output_file}" "  class Context\n")
  file(APPEND "${output_file}" "  {\n")
  file(APPEND "${output_file}" "    template <typename T>\n")
  file(APPEND "${output_file}" "    static T *finish_create(T *result)\n")
  file(APPEND "${output_file}" "    {\n")
  file(APPEND "${output_file}" "      if constexpr (requires { result->initialize(); }) {\n")
  file(APPEND "${output_file}" "        result->initialize();\n")
  file(APPEND "${output_file}" "      }\n\n")
  file(APPEND "${output_file}" "      return result;\n")
  file(APPEND "${output_file}" "    }\n\n")
  file(APPEND "${output_file}" "    mutable std::shared_mutex mutex_;\n\n")
  file(APPEND "${output_file}" "${fields}")
  file(APPEND "${output_file}" "\n  public:\n")
  file(APPEND "${output_file}" "    Context() = default;\n")
  file(APPEND "${output_file}" "${public_getters}")
  file(APPEND "${output_file}" "\n  private:\n")
  file(APPEND "${output_file}" "${private_factories}")
  file(APPEND "${output_file}" "  };\n")
  file(APPEND "${output_file}" "} // namespace context\n")
endfunction()
